name: Lint

on:
  push:
    branches:
      - main
      - preprod
      - prod

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint . --ext .ts --max-warnings=0
